const MENU = [
  // КОМБО
  { id:1,  cat:'combos',   name:'Комбо №1',          weight:'800 г',          desc:'Бешбармак + Салат Ачик-чучук + Айран. Сытный классический набор для одного — всё в одном.',           price:2900, origPrice:3300, img:'images/food_combo1.jpg',      emoji:'🥘', gradient:['#1A237E','#C8943A'], rating:89, reviews:24 },
  { id:2,  cat:'combos',   name:'Комбо №2',          weight:'650 г',          desc:'Манты (6 шт) + Корейская морковь + Чёрный чай. Лёгкий и вкусный перекус в любое время.',             price:1700, origPrice:1950, img:null,                            emoji:'🥟', gradient:['#1B4D2E','#E63946'], rating:87, reviews:18 },
  { id:3,  cat:'combos',   name:'Комбо Семейное',    weight:'2.2 кг',         desc:'Бешбармак + Плов + 4 Айрана + Чак-чак. Большой набор для всей семьи — экономия 1 300 ₸!',            price:6500, origPrice:7800, img:null,                            emoji:'🍱', gradient:['#4A0E0E','#C8943A'], rating:95, reviews:41 },
  // ВТОРЫЕ
  { id:10, cat:'second',   name:'Бешбармак',         weight:'500 г',          desc:'Традиционное казахское блюдо из варёного мяса с тестом (жайма) и наваристым бульоном.',               price:2500, origPrice:null, img:'images/food_beshbarmak.jpg',   emoji:'🥘', gradient:['#6B2121','#C8943A'], rating:94, reviews:67 },
  { id:11, cat:'second',   name:'Манты',             weight:'350 г (6 шт)',   desc:'Сочные паровые пельмени с рубленым мясом и луком. Подаются со сметаной и зеленью.',                  price:1200, origPrice:null, img:'images/food_manti.jpg',         emoji:'🥟', gradient:['#5C3317','#D4874E'], rating:91, reviews:53 },
  { id:12, cat:'second',   name:'Плов',              weight:'400 г',          desc:'Ароматный рис, тушёный с бараниной, морковью и восточными специями. Золотистый, рассыпчатый.',       price:1500, origPrice:null, img:null,                            emoji:'🍚', gradient:['#7A5C00','#E8B76A'], rating:90, reviews:38 },
  { id:13, cat:'second',   name:'Куырдак',           weight:'300 г',          desc:'Жареные субпродукты с луком и ароматными казахскими специями. Тёплое блюдо с богатым вкусом.',        price:1800, origPrice:null, img:null,                            emoji:'🍖', gradient:['#4A1010','#B84040'], rating:85, reviews:22 },
  { id:14, cat:'second',   name:'Шашлык баранина',   weight:'300 г',          desc:'Сочный шашлык из молодого ягнёнка, маринованный и приготовленный на живых углях.',                   price:2200, origPrice:null, img:null,                            emoji:'🍢', gradient:['#3D1F00','#C8943A'], rating:93, reviews:31 },
  // ПЕРВЫЕ
  { id:20, cat:'first',    name:'Лагман',            weight:'450 г',          desc:'Густой суп с тянутой домашней лапшой, говядиной и свежими овощами в ароматном бульоне.',             price:1300, origPrice:null, img:'images/food_lagman.jpg',        emoji:'🍜', gradient:['#8B2500','#FF6B3D'], rating:92, reviews:29 },
  { id:21, cat:'first',    name:'Шурпа',             weight:'400 г',          desc:'Наваристый бараний суп с картофелем, морковью, луком и пряностями. Согревает и насыщает.',           price:1100, origPrice:null, img:null,                            emoji:'🥣', gradient:['#5C3300','#C8943A'], rating:88, reviews:17 },
  { id:22, cat:'first',    name:'Сорпа',             weight:'350 г',          desc:'Традиционный казахский прозрачный бульон из баранины. Чистый, ароматный, укрепляет силы.',           price:900,  origPrice:null, img:null,                            emoji:'🍲', gradient:['#2D4A1E','#66BB6A'], rating:86, reviews:14 },
  // САЛАТЫ
  { id:30, cat:'salads',   name:'Оливье',            weight:'200 г',          desc:'Классический салат с колбасой, картофелем, огурцами и майонезом. Всегда свежий.',                    price:700,  origPrice:null, img:null,                            emoji:'🥗', gradient:['#1B4D2E','#4CAF50'], rating:82, reviews:15 },
  { id:31, cat:'salads',   name:'Ачик-чучук',        weight:'180 г',          desc:'Традиционный казахский салат из свежих помидоров и лука. Лёгкий, освежающий, без заправки.',         price:500,  origPrice:null, img:null,                            emoji:'🍅', gradient:['#6B1414','#E53935'], rating:88, reviews:21 },
  { id:32, cat:'salads',   name:'Морковь по-кор.',   weight:'150 г',          desc:'Острая маринованная морковь по-корейски с кунжутом, чесноком и кориандром.',                         price:450,  origPrice:null, img:null,                            emoji:'🥕', gradient:['#7A3D00','#FF8C42'], rating:79, reviews:11 },
  { id:33, cat:'salads',   name:'Цезарь',            weight:'280 г',          desc:'Классический цезарь: куриное филе-гриль, листья романо, пармезан, крутоны, соус цезарь.',            price:1100, origPrice:null, img:null,                            emoji:'🫛', gradient:['#2E5218','#7CB342'], rating:86, reviews:19 },
  // ФАСТ-ФУД
  { id:40, cat:'fastfood', name:'Самса',             weight:'150 г',          desc:'Хрустящая слоёная выпечка из тандыра с сочной начинкой из рубленого мяса и лука.',                   price:400,  origPrice:null, img:null,                            emoji:'🫓', gradient:['#5C4000','#C8943A'], rating:91, reviews:45 },
  { id:41, cat:'fastfood', name:'Баурсак',           weight:'200 г (8 шт)',   desc:'Традиционные казахские жареные пончики. Мягкие внутри, золотистые снаружи. К чаю.',                  price:400,  origPrice:null, img:null,                            emoji:'🍩', gradient:['#4A2800','#C8943A'], rating:87, reviews:33 },
  // НАПИТКИ
  { id:50, cat:'drinks',   name:'Айран',             weight:'500 мл',         desc:'Освежающий традиционный кисломолочный напиток. Натуральный, холодный.',                                price:300,  origPrice:null, img:null,                            emoji:'🥛', gradient:['#1A3A5C','#42A5F5'], rating:84, reviews:28 },
  { id:51, cat:'drinks',   name:'Кумыс',             weight:'300 мл',         desc:'Натуральный кисломолочный напиток из кобыльего молока. Традиционный казахский напиток.',               price:500,  origPrice:null, img:null,                            emoji:'🍶', gradient:['#4A3000','#C8943A'], rating:88, reviews:16 },
  { id:52, cat:'drinks',   name:'Чёрный чай',        weight:'400 мл',         desc:'Крепкий казахский чёрный чай, заваренный в чайнике с молоком. Согревает и бодрит.',                   price:250,  origPrice:null, img:null,                            emoji:'🫖', gradient:['#3D1C00','#A0522D'], rating:81, reviews:22 },
  { id:53, cat:'drinks',   name:'Coca-Cola 0.5л',    weight:'500 мл',         desc:'Холодная Coca-Cola в запечатанной бутылке.',                                                           price:400,  origPrice:null, img:null,                            emoji:'🥤', gradient:['#5C0000','#CC0000'], rating:77, reviews:14 },
  { id:54, cat:'drinks',   name:'Сок апельсиновый',  weight:'300 мл',         desc:'Натуральный апельсиновый сок без добавок, 300мл.',                                                     price:450,  origPrice:null, img:null,                            emoji:'🍊', gradient:['#7A4300','#FF9800'], rating:83, reviews:19 },
  // ДЕСЕРТЫ
  { id:60, cat:'desserts', name:'Чак-чак',           weight:'200 г',          desc:'Медовая казахская выпечка из тонкого теста, залитая горячим мёдом с орехами.',                         price:600,  origPrice:null, img:null,                            emoji:'🍯', gradient:['#5C3A00','#D4AF37'], rating:93, reviews:37 },
  { id:61, cat:'desserts', name:'Мороженое',         weight:'160 г (3 шара)', desc:'Три шарика сливочного пломбира с вареньем и шоколадным топпингом.',                                    price:550,  origPrice:null, img:null,                            emoji:'🍨', gradient:['#1A1A5C','#7986CB'], rating:85, reviews:23 },
];
module.exports = { MENU };
